#!/usr/bin/env sh

# Build specific modules
export MODULES="zepto event deferred callbacks touch ajax"

cd zepto
npm install
npm run-script dist
cd ..

if [ -f index.js ]; then
  rm index.js;
fi

cat zepto/dist/zepto.js _index.js > index.js
